#  FROM python:3.8-alpine
#  FROM python:3.7-slim
FROM python:3.7

WORKDIR /app

COPY app/ .

RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["/usr/local/bin/gunicorn","--bind",":8080","--workers=1","--timeout=0","--threads=8","app:app"]